# This file was generated by GoReleaser. DO NOT EDIT.
cask "marquee" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "fa7bd829318b1b584cf28484b906d1514dd53422b4ec778caab948dbab8afe31"
      url "https://github.com/jellehuibregtse/marquee/releases/download/v#{version}/marquee_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fa20658fec44cf1f81e08d63ea348c7ec0c6abf43cfcad6357fe34075f778228"
      url "https://github.com/jellehuibregtse/marquee/releases/download/v#{version}/marquee_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "05af92c615eb44ee71d1e652aa3eed9fe75136afad8c9ad7971d63353c51eeaf"
      url "https://github.com/jellehuibregtse/marquee/releases/download/v#{version}/marquee_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4b8c308201020873ebcca07e811d2eb8666400ce35f591290ba8d1713c7539b7"
      url "https://github.com/jellehuibregtse/marquee/releases/download/v#{version}/marquee_#{version}_linux_arm64.tar.gz"
    end
  end

  name "marquee"
  desc "Local reverse proxy that shows branch, worktree, and PR info in a bar injected into your dev server's HTML"
  homepage "https://github.com/jellehuibregtse/marquee"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "marquee"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/marquee"]
    end
  end

  # No zap stanza required

end
