# This file was generated by GoReleaser. DO NOT EDIT.
cask "marquee" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "d5fb5256c7d0b5f4a7a3cdb4c3c8eb3636d81eb1ac4f8c31341daad8bb21931c"
      url "https://github.com/jellehuibregtse/marquee/releases/download/v#{version}/marquee_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9f5b8c9786efaf59ad2ae80af4f186fb187737cf344abbbde851fd5afea46720"
      url "https://github.com/jellehuibregtse/marquee/releases/download/v#{version}/marquee_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "500079ac0592c415a1feb620e3242993ec45ceb2296d6811cf3512aa55731312"
      url "https://github.com/jellehuibregtse/marquee/releases/download/v#{version}/marquee_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bb13319dc2602acdc78f4d468e0ee99eec6d5ce725a5e7e69f1368c849618c85"
      url "https://github.com/jellehuibregtse/marquee/releases/download/v#{version}/marquee_#{version}_linux_arm64.tar.gz"
    end
  end

  name "marquee"
  desc "Local reverse proxy that shows branch, worktree, and PR info in a bar injected into your dev server's HTML"
  homepage "https://github.com/jellehuibregtse/marquee"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "marquee"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/marquee"]
    end
  end

  # No zap stanza required

end
