# This file was generated by GoReleaser. DO NOT EDIT.
cask "marquee" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "574dc1114d054985160b9cf8220720b1e49bc795c22f9590b21a6ab06af49f4d"
      url "https://github.com/jellehuibregtse/marquee/releases/download/v#{version}/marquee_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "40244945261527889e8ebcaa83b620664e7373280a54c5d11cb6b64b63212632"
      url "https://github.com/jellehuibregtse/marquee/releases/download/v#{version}/marquee_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "315e25159474e4648641b2582f645bd73e8acb8b0782aa90b74668fc95a85348"
      url "https://github.com/jellehuibregtse/marquee/releases/download/v#{version}/marquee_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "159f0b416a05b4c1552ce3152e6e6286af01cb35040ac5e14b281339ee3f03d4"
      url "https://github.com/jellehuibregtse/marquee/releases/download/v#{version}/marquee_#{version}_linux_arm64.tar.gz"
    end
  end

  name "marquee"
  desc "Local reverse proxy that shows branch, worktree, and PR info in a bar injected into your dev server's HTML"
  homepage "https://github.com/jellehuibregtse/marquee"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "marquee"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/marquee"]
    end
  end

  # No zap stanza required

end
